declare class Update implements Saveable {
  defaults: Record<string, any>;
  saveKey: string;
  version: string;
  saveVersion: string;
  updateSteps: {
    "0.4.0": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.4.4": ({ saveData }: { saveData: any }) => void;
    "0.4.15": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.4.17": ({ saveData }: { saveData: any }) => void;
    "0.4.18": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.5.0": ({ playerData }: { playerData: any }) => void;
    "0.5.2": ({ saveData }: { saveData: any }) => void;
    "0.5.5": ({ saveData }: { saveData: any }) => void;
    "0.5.7": ({ saveData }: { saveData: any }) => void;
    "0.5.8": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.6.0": ({ saveData }: { saveData: any }) => void;
    "0.6.1": ({ saveData }: { saveData: any }) => void;
    "0.6.5": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.7.1": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.7.4": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.7.6": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.1": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.3": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.4": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.9": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.12": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.14": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.8.15": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.9.0": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
    "0.9.4": ({ playerData, saveData }: { playerData: any; saveData: any }) => void;
  };
  constructor();
  checkForNewerVersionOnInterval(): void;
  minUpdateVersion(version: any, saveData: any): boolean;
  isNewerVersion(version: any, compareVersion: any): boolean;
  isOlderVersion(version: any, compareVersion: any): boolean;
  getBackupButton(): [HTMLElement, string];
  automaticallyDownloadBackup(button: any, settingsData: any): void;
  check(): void;
  static moveIndex: (arr: any, to: any, from?: number, defaultVal?: number) => any;
  static addPokemonToSaveData: (saveData: any, pokemonId: any) => void;
  static renamePokemonInSaveData: (saveData: any, oldName: any, newName: any) => void;
  getPlayerData(): any;
  setPlayerData(playerData: any): void;
  getSaveData(): any;
  setSaveData(saveData: any): void;
  getSettingsData(): any;
  setSettingsData(settingsData: any): void;
  fromJSON(json: any, initial?: boolean): void;
  toJSON(): Record<string, any>;
}
